### ISSUE TITLE
Example how to use

### ISSUE THREAD

**Issue by marvincaspar** [XciD/loxone-ws#13]
Hi,

first of all, thanks for this package. 

Can you please add some example code in the readme how the package should be used? E.g. how to connect, how to disconnect, how to receive new item values, how to set a specific value,...

**Comment by XciD** [comment]
Hello, 

I will update the Readme when I will have more time.

If you want some example, you can inspire on this library:

https://github.com/XciD/loxone-prometheus-exporter/blob/master/main.go
