### ISSUE TITLE
Events not accessible

### ISSUE THREAD

**Issue by marcokernler** [XciD/loxone-ws#14]
Hi,

i've tried your [example](https://github.com/XciD/loxone-prometheus-exporter/blob/master/main.go) mentioned in #13. But unfortunately i wasn't able compile the app since the [`Events`](https://github.com/XciD/loxone-prometheus-exporter/blob/master/main.go#L134) field wasn't accessible within the select to receive incoming events.

Are there a missing method on `WebsocketInterface` wich will return the event channel (see below) or do i missing something?

```golang

//
type WebsocketInterface interface {
    ....
    GetEventsChan() chan *events.Event
}

//
for {
    // get events channel
    events := lox.GetEventsChan()
    
    select {
    case <-ctx.Done():
        log.Infof("Shutting Down")

    case event := <-events:
       if eventMetric, ok := globalStates[event.UUID]; ok {
            eventMetric.update(event.Value)
        } else {
            log.Debugf("event unknown: %+v\n", event)
        }
    }
}
```

Thank you!

**Comment by XciD** [comment]
Hello,

You should be able to read event with: `<-lox.Events`

**Comment by nickngsr** [comment]
Hi I seem to be having the same issue, sorry if I'm being incompetent, as the New function returns WebsocketInterface and not *Loxone how do I access the Events property in the Loxone struct? Using <-lox.Events does not compile. 

Either changing the return signature back to *Loxone originally changed here 0484f7f9c0f02e16f7177af2377f37d6991c0ccc, or adding a getter for the Event channel remedies this.

Or is it now recommended to utilise hooks for specific UUIDs and PumpEvents?

**Comment by XciD** [comment]
Hello, 

Sorry for the delay, didn't have much time to look.

Fixed on master
