### ISSUE TITLE
SHA256 Question/Help

### ISSUE THREAD

**Issue by marcokernler** [XciD/loxone-ws#18]
Hallo @XciD,

i have another pull-request in the pipeline but i need your help here: We have tried to connect to a miniserver via the library but the connection has failed with an 401 error received from the miniserver. 

After investigation we found that the miniserver will respond to the `/jdev/sys/getkey2/{user}` request, not only with the key and salt, but also with the hashing algorithm one should use to hash the `{password}:{userSalt}` within the process of getting an token.

We have successfully tested the implementation, but the last step would be to get the value of the field `hashAlg` from the `/jdev/sys/getkey2/{user}` request. In my understanding the value should be available within `createToken(user string, password string, uniqueID string)`, to pass the hashAlg- value to the `hashUser(user string, password string, salt string, oneTimeSalt string)` method. There we can then use the appropriate algorithm to hash the password/salt values.

Can you please point me in the right direction to accomplish this?

Thank you Marco

**Comment by XciD** [comment]
To be honest, I don't remember well how it's done.

I've reverse engineer this repo to find the right way of doing it
https://github.com/Loxone/lxcommunicator
