### ISSUE TITLE
Added features

### ISSUE THREAD

**Issue by nickngsr** [XciD/loxone-ws#20]
I've had a go at implementing Loxone DNS, a download socket and some rudimentary version checks, I've also fixed a few goroutine issues. The fork is [here](https://github.com/nickngsr/loxone-ws). 

I have however fundamentally changed the way that new sockets are instantiated so can't really just issue a pull request unless you're happy for a very breaking change to make its way into this repo. Some examples of the new socket creation are in the loxone_test.go file.

**Comment by XciD** [comment]
Hello @nickngsr,

I be glad to check your code, don't hesitate to create a PR.

If it break, we will just change the version.
